### ISSUE TITLE
JPEG-like artifacts

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [anishathalye/neural-style#100]
I experience artifacts in every picture that neural-style creates.

![zb416](https://user-images.githubusercontent.com/18123801/29239774-ae6ba1f8-7f56-11e7-93a6-e84a84dc18e2.jpg)

![2](https://user-images.githubusercontent.com/18123801/29239777-c1b1447a-7f56-11e7-8e2d-3e6a206efb2e.jpg)

Even if I use png as output.

How do I prevent them?

**Comment by anishathalye** [comment]
Maybe try playing around with total variation (TV) regularization loss weight?

**Comment by jppgks** [comment]
Here's a an article on the topic from Distill that I enjoyed: https://distill.pub/2016/deconv-checkerboard/

**Comment by ErfolgreichCharismatisch** [comment]
@jppgks Beyond me what they did. Please share what to change in anis code to apply it.

**Comment by jppgks** [comment]
@ErfolgreichCharismatisch If I understand correctly, the artifacts are due to the network (VGG in this case) and what stride and size are used for convolution layers. Seems to me like you would need to tweak the network itself in order to reduce artifacts.

**Comment by ErfolgreichCharismatisch** [comment]
@jppgks which hyperparameters would you tweak?

**Comment by anishathalye** [comment]
Hmm, the article that @jppgks mentioned is relevant when using an algorithm like [Perceptual Losses for Real-Time Style Transfer and Super-Resolution](https://cs.stanford.edu/people/jcjohns/eccv16/), but I don't think it applies to the algorithm we're using here (we don't have any deconvolution kernels).

Increasing TV weight might help. Another trick you could use is rendering at a higher resolution and then using a smooth downscaling algorithm.

**Comment by limchaos** [comment]
Hi,I got a problem @anishathalye,  which is the generator in this network ,it seems only a VGG19, and I don't think VGG19 can generate a image 🍡 , I mean it's a feature map
