### ISSUE TITLE
Upload vgg weights on another faster host

### ISSUE THREAD

**Issue by oxydron** [anishathalye/neural-style#103]
Very slow download speed...

![image](https://user-images.githubusercontent.com/331134/32811964-b1d851c4-c989-11e7-99c7-7ee40be6c77e.png)

And I have a 20mb download link (2mb/s download)

**Comment by anishathalye** [comment]
<img width="372" alt="screen shot 2017-11-16 at 1 44 05 pm" src="https://user-images.githubusercontent.com/3526486/32909275-3d477e7e-cad4-11e7-9fe4-5d0faf074e75.png">

It's fast for me. Probably just your network?
