### ISSUE TITLE
Wrong data

### ISSUE THREAD

**Issue by HyunJun-Jo** [anishathalye/neural-style#104]
I followed the instructions, and I run the neural_style.py like below

> python neural_style.py --content example/loul.jpg --styles examples/2-style2.jpg --output test1.jpg

But it gives a below message.

> You're using the wrong VGG19 data. Please follow the instructions in the README to download the correct data.

I think the path of the mat file is wrong. I put it in the neural_style folder.
Is there anything wrong?

Thanks, in advance.

**Comment by anishathalye** [comment]
You're using the wrong data.

See #4 #6 #12 #25 #39 #43 #46 #69 #74 #75
