### ISSUE TITLE
why times 0.256 in white noise image

### ISSUE THREAD

**Issue by weiqingccao** [anishathalye/neural-style#106]
Hi anishathalye,
I was looking at stylize.py file and found that you times 0.256 to get white noise image. May I ask why you did that?
BTW, your work is amazing!

**Comment by anishathalye** [comment]
That code was written in commit 7f9d75675a7ce83617ca91ff48a11002c757c114, almost exactly two years ago. I don't remember why I did that... I think it was to get random noise with a small stdev.
