### ISSUE TITLE
Is there a way to extract the style features i.e. corresponding to relu5_1 ?

### ISSUE THREAD

**Issue by vikiboy** [anishathalye/neural-style#107]
Is there a way to display the style features like the ones shown in Fig. 1 of the original "A Neural Algorithm of Artistic Style" paper ( Style Reconstructions ‘conv5 1’ (e) ) ?

I tried modifying the code to save the `style_features` list in stylize.py, which has 5 dictionary keys corresponding to the VGG layers, and the values corresponding to arrays of size (64,64), (128,128), (256,256),(512,512), (512,512).

I am guessing these are the style features of the style image. Is there any way I can visualize these the same way as shown in the paper ?

**Comment by anishathalye** [comment]
The code isn't set up to do this, but you could do it by choosing your style layers appropriately [here](https://github.com/anishathalye/neural-style/blob/master/stylize.py#L13), supplying an arbitrary content image, and setting content weight to `0`.
