### ISSUE TITLE
neural_style.py: error: ambiguous option

### ISSUE THREAD

**Issue by Liangmp** [anishathalye/neural-style#108]
I am running it in windows cmd:
python neural_style.py --content 1-content.jpg --style 1-style.jpg --output test1.jpg

And I get an error:
neural_style.py: error: ambiguous option: --style could match --styles, ---style-scales, --style-weight, --style-layer-weight-exp, --style-blend-weights

**Comment by anishathalye** [comment]
Use `--styles`

**Comment by Liangmp** [comment]
Thank you very much. Problem fixed and I'm very happy that I got the expected output, althought it takes me almost 5 hours to run 1-content.jpg with 1000 iterations.

**Comment by anishathalye** [comment]
It's much faster with a fast GPU -- takes me a minute or two on a 1080 Ti.
