### ISSUE TITLE
The effect of different layers of CNN 

### ISSUE THREAD

**Issue by limitforever** [anishathalye/neural-style#110]
Hello,anishathalye!
   In your code,I found that you defined the content network structure as CONTENT_LAYERS = ('relu4_2', 'relu5_2'),while the original paper defined it as 'con4_2',and there are also other different desighed such as 
'relu4_2'.
   So my question is : what are the differences among them? Is it better for CONTENT_LAYERS = ('relu4_2', 'relu5_2')?
   I'll be appreciated if you could reply.

**Comment by anishathalye** [comment]
Uh I did some not-super-scientific experimentation a while ago and I think the thing I chose produced visually nice results. Feel free to experiment with different choices there. If you do some principled experiments and find that a particular setting is consistently better, feel free to submit a pull request :)
