### ISSUE TITLE
-init image option?

### ISSUE THREAD

**Issue by minxdragon** [anishathalye/neural-style#114]
I've been using neural-style for a long time in Torch but I'm looking to work more with Tensorflow and I'm trying to replicate my results. 

is there a flag for something like -init image? where it starts from the image and builds up from there rather than from a blank space.

**Comment by anishathalye** [comment]
https://github.com/anishathalye/neural-style/blob/master/neural_style.py#L94

**Comment by minxdragon** [comment]
ah perfect thankyou, I thought I checked the source but I missed that
/facepalm. it's working perfectly now with my iterative script!
