### ISSUE TITLE
You have a photo and paint this photo in your own style and you want neural style to create a painting in your style based on another photo.

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [anishathalye/neural-style#115]
How would I have to change it for it to set the right parameters when entering an original picture and the finished picture.

For instance, you have a photo and paint this photo in your own style and you want neural style to create a painting in your style based on another photo.

**Comment by anishathalye** [comment]
neural style doesn't do paired image translation. you can just give it your style image (the painting) along with the new source image and it'll synthesize a pastiche.
