### ISSUE TITLE
Error converting image

### ISSUE THREAD

**Issue by djcopley** [anishathalye/neural-style#119]
When I attempt to run the neural_style on my images I receive the following error:

```
Traceback (most recent call last):
  File "/Users/djcopley/Documents/GitHub/NeuralStyle/neural_style.py", line 219, in <module>
    main()
  File "/Users/djcopley/Documents/GitHub/NeuralStyle/neural_style.py", line 121, in main
    content_image = imread(options.content)
  File "/Users/djcopley/Documents/GitHub/NeuralStyle/neural_style.py", line 203, in imread
    img = scipy.misc.imread(path).astype(np.float)
TypeError: float() argument must be a string or a number, not 'JpegImageFile'
```

I've done some digging and it looks like scipy.misc.imread is deprecated. This shouldn't however bring the program to a halt. In addition, the documentation says imread should return an np.ndarray object, however, looking at the traceback, it appears to be returning a 'JpegImageFile' object. Any thoughts to why this might be happening? I am running Mac OSX if that wasn't clear from the traceback. Thanks :)

**Comment by djcopley** [comment]
By breaking the method chain apart, I was able to fix this issue. 
```
img = scipy.misc.imread(path).astype(np.float)
```
Is now -
```
img = scipy.misc.imread(path)
img = img.astype(np.float)
```

**Comment by anishathalye** [comment]
it looks like those two should be equivalent

**Comment by djcopley** [comment]
They do seem to be equivalent. I would think imread() would resolve to its value and then the .astype() method would be invoked, however for some reason I was getting a type error. I couldn't figure out why it was returning a 'JpegImageFile' object instead of a numpy array either. In the interim however, splitting it up seems to have done the trick.
