### ISSUE TITLE
Data has no key 'normalization'

### ISSUE THREAD

**Issue by Irtza** [anishathalye/neural-style#12]
Error in vgg.py.. has the format of vgg changed?

the only modification i did to the clone was to run it on gpu:0 .

**Comment by anishathalye** [comment]
https://github.com/anishathalye/neural-style#requirements

https://github.com/anishathalye/neural-style/issues/6

**Comment by Irtza** [comment]
@anishathalye thankyou for pointing me to the issue, I had downloaded a different model before
