### ISSUE TITLE
No output for a long long time

### ISSUE THREAD

**Issue by Liangmp** [anishathalye/neural-style#134]
I typed the command in terminal:
python neural_style.py --content 1-content.jpg --styles 1-style.jpg --output test2.jpg --iterations 10

And I got a this warning:
/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

Even though I set --iterations as a very small number like 10, it still takes me a very long time (like hours) without outputting anything.

Could you help me point it out if there is something wrong?

**Comment by anishathalye** [comment]
Huh it shouldn't be _that_ slow unless you're running it on a huge image. See #20 

Also, using a GPU will make it a lot faster.

**Comment by Liangmp** [comment]
Thank you for your reply. I will try it again with a smaller image and see if it works.

**Comment by anishathalye** [comment]
As a test, try a really small image, e.g. 128x128: you should be able to see it work, and you can scale up from there.

**Comment by Liangmp** [comment]
That helps a lot! It works now.
