### ISSUE TITLE
Higher resolution ideas

### ISSUE THREAD

**Issue by surferek** [anishathalye/neural-style#135]
Hello, 

I've tried to create image with input content of size 3200x2600 pix and it returned me error that I have not enough memory on my GPU. So I have question what type of graphic card or how much GPU memory I would need to compute imag of that size?

**Comment by anishathalye** [comment]
That's a large image. This may not be the right algorithm for you. You could try to split the model between GPUs (#91) or implement some kind of swapping, but that seems pretty high effort. Another idea is to try https://github.com/lengstrom/fast-style-transfer.

**Comment by surferek** [comment]
Thanks! It seems that my gpu cart is too weak, I will try another solutions  also with fast-style-transfer. Thanks for help and quick reply! :)
