### ISSUE TITLE
How to run it in an application not as a script?

### ISSUE THREAD

**Issue by sonjadeissenboeck** [anishathalye/neural-style#138]
Hi there! I'd like to use that awesome project for an application of mine (it's only for private fun!).
However, I'm new to Python and can't figure out how to apply the neural_style to any of my images..

Could anybody help?

So far I have:
- imported all the files to PyCharm
- installed all requirements

Thanks in advance!

**Comment by anishathalye** [comment]
You can use the command line interface. See the readme for examples, or run `python neural_style.py --help` for usage info.

**Comment by sonjadeissenboeck** [comment]
Hmm but I don't want to use the command line, that's why I'm looking for a workaround..

**Comment by anishathalye** [comment]
There is only a command-line interface. You could implement a graphical interface if you want one.
