### ISSUE TITLE
error when running sample picture

### ISSUE THREAD

**Issue by may811204** [anishathalye/neural-style#14]
Got this error message:
![image](https://cloud.githubusercontent.com/assets/8717276/14675818/5400c33e-073d-11e6-9f8d-3a042e4e3dbf.png)
wrong with the command or anything else?

**Comment by anishathalye** [comment]
Umm not entirely sure why that isn't working. It works on my system. Do you have all the dependencies installed?

**Comment by may811204** [comment]
for the dependencies, I've checked as followed:
![image](https://cloud.githubusercontent.com/assets/8717276/14708867/21c92e88-0800-11e6-8c7b-221e1f564ec3.png)
it seems no error when importing the modules needed.
Also, the python version is 2.7.6 on my machine.
thanks for answering!

**Comment by anishathalye** [comment]
see https://github.com/andersbll/neural_artistic_style/issues/8 ?

**Comment by jeromeyoon** [comment]
@may811204 I have the same problem and i found a solution from [https://github.com/tensorflow/tensorflow/issues/1541].

You should import scipy.misc before import tensorflow as tf

**Comment by anishathalye** [comment]
Do you want to submit a PR or should I edit it myself?

**Comment by anishathalye** [comment]
Fixed in #16.
