### ISSUE TITLE
not callable from python

### ISSUE THREAD

**Issue by bizso09** [anishathalye/neural-style#147]
Could you refactor the code such that it's actually callable from another python application as an imported library? Thank you

**Comment by anishathalye** [comment]
This is not something I have the bandwidth to work on currently, but I'd welcome a pull request to do this.

If you want to use the code as-is, I can suggest a couple workarounds:
- Call `stylize()` (from [here](https://github.com/anishathalye/neural-style/blob/master/stylize.py#L33)) directly (perhaps using `neural_style.py:main()` as a guide to see how `stylize()` is called
- Shell out to `neural_style.py`
