### ISSUE TITLE
"You're using the wrong VGG19 data."

### ISSUE THREAD

**Issue by FlamesoFF** [anishathalye/neural-style#148]
**Error:**
```
raise ValueError("You're using the wrong VGG19 data. Please follow the instructions in the README to download the correct data.")
ValueError: You're using the wrong VGG19 data. Please follow the instructions in the README to download the correct data.
```

**Script:**
`py neural_style.py --network imagenet-vgg-verydeep-19.mat --content %content%/%filename% --styles %styles%/%stylename% --output %output%/%filename%  --overwrite`

**MD5:**
`106118b7cf60435e6d8e04f6a6dc3657`

Network was downloaded from this URL: http://www.vlfeat.org/matconvnet/models/imagenet-vgg-verydeep-19.mat

What I'm doing wrong? @anishathalye Seems like the data is broken.

**Comment by anishathalye** [comment]
Please try using the latest version of `neural-style` (as of this post, 556448aafb0b1579e805c3e27df190b78802040a).

**Comment by FlamesoFF** [comment]
@anishathalye Yes, new version is working.

**Comment by anishathalye** [comment]
Great!
