### ISSUE TITLE
Error in reading the image

### ISSUE THREAD

**Issue by antgr** [anishathalye/neural-style#15]
Hi,
I face the following error,
I added some printing in order to debug it. 
def imread(path):
    print "path is ", path
    img = scipy.misc.imread(path)
    print "img is ", img
    return scipy.misc.imread(path).astype(np.float)

The reading  of the image is working manually in a ipython notebook, but not with the script. 
Any ideas?

>python neural_style.py --content /home/antgr/input-image.jpg  --styles /home/antgr/style.jpg --output /home/antgr/output.jpg
path is  /home/antgr/input-image.jpg
img is  < PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=1600x1200 at 0x7FF3CA714710 >
Traceback (most recent call last):
  File "neural_style.py", line 153, in <module>
    main()
  File "neural_style.py", line 83, in main
    content_image = imread(options.content)
  File "neural_style.py", line 144, in imread
    return scipy.misc.imread(path).astype(np.float)
TypeError: float() argument must be a string or a number

**Comment by anishathalye** [comment]
Is your `$PYTHONPATH` the same when running IPython notebook / the non-interactive interpreter?

This looks like something could be wrong with your SciPy or Pillow installation.

**Comment by TenSoon** [comment]
I had the same error. The message is misleading. The actual fault is somewhere in stylize.py because it magically started working when i moved `from stylize import stylize` AFTER `import scipy.misc`.

**Comment by polo2ro** [comment]
thanks for the tip, it started working for me too with this change

**Comment by anishathalye** [comment]
Hmm, import order shouldn't affect things like that 😕

**Comment by DrewWham** [comment]
Same error here and same fix

**Comment by anishathalye** [comment]
Anyone want to submit a PR?

**Comment by anishathalye** [comment]
Fixed by #16.
