### ISSUE TITLE
如何使用多GPU同时运算

### ISSUE THREAD

**Issue by pearandli** [anishathalye/neural-style#153]
RT，我跑的时候发现只在一个GPU上有loading，但我接了两个显卡，并且程式一开始也认到了两张。如何才能让两张显卡同时进行运算呢？

**Comment by anishathalye** [comment]
Hi, sorry, I don't speak Chinese.

Google Translate gives the following:

> How to use multiple GPU simultaneous operations
>
> RT, when I ran, I found that there was loading on only one GPU, but I took two graphics cards and the program recognized two at the beginning. How can I get two graphics cards to operate at the same time?

This code does not support parallelizing across multiple GPUs. See #91.

**Comment by pearandli** [comment]
thankyou!
