### ISSUE TITLE
Why I got strange results?

### ISSUE THREAD

**Issue by david658** [anishathalye/neural-style#155]
Dear friends,

Recently I have tested the program on my notebook but got strange results. The output file contains just random distributed dots,  neither content  nor  style appear as in the input files.  After installing Pillow, Scipy 1.1.0 and tensorflow 1.14.0 (not tensorflow-gpu), and checking 
>>> import PIL
>>> PIL.__version__
'6.2.0'
>>> import scipy
>>> scipy.__version__
'1.1.0'
>>> import numpy
>>> numpy.__version__
'1.16.5'
>>> import tensorflow as tf
>>> tf.__version__
'1.14.0'

Then  I ran the following  command in anaconda prompt: 
python neural_style.py --content ./content/1-content.jpg --styles ./style/1-style.jpg --output ./output/output.jpg --checkpoint-output ./output/test_%d.jpg  --checkpoint-iterations 100 --overwrite. 
The program goes through with no fatal errors, but the output image seems to be not right.
![test_1000](https://user-images.githubusercontent.com/56370470/66526699-815ec380-eaf1-11e9-88e9-4be97273245d.jpg)

Could anyone please kindly tell me what is wrong with my practice?  

Many thanks, 

David

**Comment by anishathalye** [comment]
It's hard to debug this sort of thing.

Could you try running the following, which uses the example inputs:

```bash
time python neural_style.py --content examples/1-content.jpg --styles examples/1-style.jpg --output new.png --iterations 1000 --overwrite
```

**Comment by david658** [comment]
Thank you for your prompt reply. I 'm trying your command and will upload the new results after 6 hour running  on my laptop.  By the way, I have no GPU installed on my laptop, so I install tensorflow 1.14.0, rather than tensorflow-gpu 1.14.0.  Can this cause problem?

**Comment by anishathalye** [comment]
No that shouldn’t cause problems

**Comment by david658** [comment]
I have run with your command, and got some error

content loss: 2.15407e+06
  style loss: 5.86155e+07
     tv loss: nan
  total loss: nan
C:\CV\NST_MIT\stylize.py:202: RuntimeWarning: invalid value encountered in less
  if this_loss < best_loss:
Traceback (most recent call last):
  File "neural_style.py", line 289, in <module>
    main()
  File "neural_style.py", line 236, in main
    checkpoint_iterations=options.checkpoint_iterations,
  File "C:\CV\NST_MIT\stylize.py", line 206, in stylize
    img_out = vgg.unprocess(best.reshape(shape[1:]), vgg_mean_pixel)
AttributeError: 'NoneType' object has no attribute 'reshape'

The output new.png is empty 
![new](https://user-images.githubusercontent.com/56370470/66624599-bef24800-ebe8-11e9-81e3-b79eade09cee.png)

My system is Anaconda 3 (Python3.7.3) on Windows 8.1.

**Comment by anishathalye** [comment]
The `nan` losses look suspicious. I'm not sure why you're getting those. Are you using the latest version of the code?

I get the following output:

```
content loss: 760838
  style loss: 257111
     tv loss: 54628.2
  total loss: 1.07258e+06
```

And it produces the following:

![new](https://user-images.githubusercontent.com/3526486/66676448-7614b080-ec35-11e9-8236-603d86f8757d.png)

**Comment by david658** [comment]
Yes, I downloaded your programs two weeks ago, so they should be the latest version. The MD5 number of the vgg I used is
8ee3263992981a1d26e73b3ca028a123. Is this version ok to run your program?

**Comment by anishathalye** [comment]
Oh maybe that's the issue? I don't remember which old versions work, but the current recommended version has MD5 hash `106118b7cf60435e6d8e04f6a6dc3657 ` (see https://github.com/anishathalye/neural-style#data-files).

**Comment by david658** [comment]
Thank you for your help and advice. I have updated VGG 19, but still can not get right results. 
Then I downgraded Python from 3.7 to 3.5, and Tensorflow from 1.14 to 1.9. It finally worked!  Now the output image looks 
![new](https://user-images.githubusercontent.com/56370470/66707946-ca588700-ed40-11e9-86cf-bf22e2b077c7.png)
Thanks again for your kind help.

**Comment by anishathalye** [comment]
Oh that's interesting… Glad you got it working!

I will leave this issue open till I can test with those specific TF versions to see if there's an incompatibility. Thanks for the detailed error reports.

**Comment by anishathalye** [comment]
I tried it on my own machine with TensorFlow 1.14, and it seems to work. Not sure why it didn't on your machine.
