### ISSUE TITLE
How recover style from filtered image?

### ISSUE THREAD

**Issue by ahvahsky2008** [anishathalye/neural-style#160]
i have pack of input images and filtered images. How get style from this?
![image](https://user-images.githubusercontent.com/8035828/71444025-a097e500-271f-11ea-8a36-e0965d675134.png)

**Comment by anishathalye** [comment]
I'm not sure exactly what you're trying to do. This code lets you take (content image, style image) and produce a new content image that's stylized like the given style image. It doesn't give you a way to recover a style image given (content image, new content image).

If you're just trying to stylize other stuff in the same way, you can try using the stylized image as the stylized image itself, and that might work all right.

**Comment by ahvahsky2008** [comment]
I want recovery style. yeap.

**Comment by anishathalye** [comment]
Okay, so this neural-style software doesn't do that, and I don't think it's possible in the general case, because there isn't enough information preserved in the output to recover the input.

Best of luck with whatever you're doing!
