### ISSUE TITLE
Allocator (GPU_0_bfc) ran out of memory trying to allocate XYGiB with freed_by_count=0.

### ISSUE THREAD

**Issue by peakpwr** [anishathalye/neural-style#162]
Hello,
I'm facing some problems as my GPU is running out of memory I guess.
When I try to run the script on a high resolution content (>3000x2500px) the script interrupts with the error: `Allocator (GPU_0_bfc) ran out of memory trying to allocate XYGiB with freed_by_count=0.`
My GPU has 11GB of RAM.

How can the script be changed so these high res pictures can be used? Or is it only possible if I use a GPU with more RAM?

**Comment by anishathalye** [comment]
See #91 and #135
