### ISSUE TITLE
When running in spyder TensorFlow 1.3

### ISSUE THREAD

**Issue by raayraay69** [anishathalye/neural-style#168]
neural_style.py: error: the following arguments are required: --content, --styles, --output
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2

**Comment by anishathalye** [comment]
As the error message says, certain flags are required.

**Comment by raayraay69** [comment]
Im sorry im so confused on this part. How do i insert these flags into the code? Do i creare a output file, content file and style file?

**Comment by anishathalye** [comment]
You don't create those files, they should already exist, and you supply them as arguments. `python neural_style.py --content <something> --styles <something> --output <something>`. E.g. if you're running in the directory of this repo, if you want to recreate the demo, you can do: `python neural_style.py --content examples/1-content.jpg --styles examples/1-style.jpg --output output.png --iterations 1000`

**Comment by raayraay69** [comment]
Ok, so if i want to download the images that you already have do i just upload them into the same directory as my code in spyder. then run
