### ISSUE TITLE
choose GPU device

### ISSUE THREAD

**Issue by kingfengji** [anishathalye/neural-style#17]
hi there, great one!

one question, I got 3 GPUs to work with, how to choose which GPU to use?

I mean, I dont want to use gpu_0 cause my monitors are connected with it.
I wish to use GPU_1 instead...

THanks!

**Comment by anishathalye** [comment]
There's currently no clean way to do it via command line switches, etc - you need to modify the code.

See how we specify that we want to use the CPU [here](https://github.com/anishathalye/neural-style/blob/master/stylize.py#L37)? You can do something similar [here](https://github.com/anishathalye/neural-style/blob/master/stylize.py#L58) and force it to use `/gpu:1`. See [this TensorFlow documentation](https://www.tensorflow.org/versions/r0.8/how_tos/using_gpu/index.html) for more information.

**Comment by anishathalye** [comment]
Btw, if you want to improve the code so that you can do this kind of stuff via command line switches, pull requests are welcome 😄

**Comment by rayrayson** [comment]
Have you tried setting the "CUDA_VISIBLE_DEVICES" environment variable before starting neural_style.py ?

See: https://devblogs.nvidia.com/parallelforall/cuda-pro-tip-control-gpu-visibility-cuda_visible_devices/

It worked for us (the Open Grid Scheduler/Grid Engine project) when we needed to control which GPU is used in a job when we did the Multi-Core Processor Binding with hwloc project:

http://gridscheduler.sourceforge.net/projects/hwloc/GridEnginehwloc.html

**Comment by rayrayson** [comment]
Have you tried setting the "CUDA_VISIBLE_DEVICES" environment variable before starting neural_style.py ?

Ref CUDA doc: http://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars

It worked for us (the Open Grid Scheduler/Grid Engine project) when we needed to control which GPU is used in a job when we did the Multi-Core Processor Binding with hwloc project:

http://gridscheduler.sourceforge.net/projects/hwloc/GridEnginehwloc.html

**Comment by anishathalye** [comment]
Going to assume this is resolved. If not, feel free to reopen.
