### ISSUE TITLE
Loss function

### ISSUE THREAD

**Issue by junk-zqm** [anishathalye/neural-style#172]
Is there something wrong with the loss function?The results are very large：
content loss: 164342
  style loss: 41753.8
     tv loss: 26570.2
  total loss: 232666

**Comment by anishathalye** [comment]
No, that's normal

**Comment by junk-zqm** [comment]
Is this data compared with zero?The result seems to be terrible.

**Comment by anishathalye** [comment]
I am not sure what you mean by compared with zero. The goal is to minimize the loss, but for the definition of the loss function in the paper, it is not necessarily possible to achieve zero loss.

**Comment by junk-zqm** [comment]
I mean how to use this loss  to judge the quality of this transfer.

**Comment by anishathalye** [comment]
I don't think there's a good answer to that question besides doing it manually/qualitatively.
