### ISSUE TITLE
Issue in content and style tranfer

### ISSUE THREAD

**Issue by Mps24-7uk** [anishathalye/neural-style#177]
Thanks for the amazing repository on style transfer. 

I have taken the pattern image as a style image and solid color image with shadows as a content image.  I want the output to have the shadows to be taken from the content image and patterns from style images. But the desired is something else. Can you help me tweaking the hyperparameters so that I get good results?

Content Image
![a](https://user-images.githubusercontent.com/31795933/132136762-413599b3-0597-413e-b1c3-23b4fbfc5f95.jpg)

Style Image
![3933197](https://user-images.githubusercontent.com/31795933/132136778-8595b7b9-4fe6-4dc5-a1fa-7acc95f06a51.jpg)

Result
![gr_result___](https://user-images.githubusercontent.com/31795933/132136788-ac6c7821-b797-446d-aae4-2e90363665fc.jpg)

Expect Result
![dr555b188c_original](https://user-images.githubusercontent.com/31795933/132136803-1a6064bc-8eed-4bfa-9da5-63bda34ee7c6.jpg)

**Comment by anishathalye** [comment]
I don't think you can get a result like that with neural style. There are probably other computer vision (perhaps ML-powered) techniques that might be able to do that, but not this repo.

**Comment by Mps24-7uk** [comment]
Thanks for the quick response. I went through the paper based on Image Localized Style Transfer to Design Clothes. The paper has some excellent results - especially in changing patterns to the clothes. They have used the same technique to transfer the style and generated the desired cloth. I am currently trying to explore similar aspects, however, haven't been so successful in getting it.  Any help would be appreciated. Thank you!!
Please find the paper link below.
[https://www.hindawi.com/journals/cin/2020/8894309/](url)
