### ISSUE TITLE
how do you run this?

### ISSUE THREAD

**Issue by eformx** [anishathalye/neural-style#179]
neural_style.py --content 'examples/1-content.jpg' --styles 'examples/1-style.jpg' --output 'out.jpg'

I run this in PyCharm and it says wrong format?  what is the correct format/synax for the images?

**Comment by anishathalye** [comment]
Can you give more details on how you're running it, and what is the error message?

You should be able to run it from the command-line, with `python neural_style.py ...`

**Comment by eformx** [comment]
Invalid syntax.  I just need how to enclose images in the call.  I tried single quotes like the original call in the console, but I am getting a syntax error?  See screenshot...
![image](https://user-images.githubusercontent.com/1794620/141820587-ec807e6f-231a-4abe-80fa-9f73a9c73033.png)

**Comment by eformx** [comment]
![image](https://user-images.githubusercontent.com/1794620/141821152-fbbea289-b048-4c44-bf57-1f50335719a3.png)

**Comment by anishathalye** [comment]
The `>>>` indicates that you're typing into a Python REPL. That's a bash command, you need to type it into a command shell.

**Comment by eformx** [comment]
tried a command prompt, same typo error.
