### ISSUE TITLE
Do you have a Docker image for this?

### ISSUE THREAD

**Issue by RichardJECooke** [anishathalye/neural-style#181]
I saw there is https://hub.docker.com/r/acarlson32/neuralstyle-tf but when I try to pull it I get a `manifest unknown` error.

**Comment by anishathalye** [comment]
I have not tried that Docker image myself before.

See related #40 and #171.

If someone submits a Dockerfile that supports both CPU and GPU via nvidia-docker, I'd be happy to merge it.

**Comment by RichardJECooke** [comment]
Thanks! Yes I realised while making my own image that trying to get the GPU to work across WSL and Docker was more work than just installing a bit of Python locally (see also https://www.logic2020.com/insight/tactical/wsl-docker-gpu-enabled-nvidia).

But while I have your attention, two questions please:

1) Is there a setting possible to run bigger images without exceeding RAM? Slower processing, but less RAM somehow. Even a 5MB image is breaking my 64GB machine.

2) Do you have any comprehensive documentation on your Javascript Tensorfire project? It looks abandoned. But I'd love to make a proper website out of it, with all the sliders for various settings, and the capability to do high resolution images. It would make deepdreamgenerator.com unnecessary.

**Comment by anishathalye** [comment]
1. Yes, but it would be a bunch of engineering work, and it would be slow. I'd recommend this alternative approach for large images: https://github.com/lengstrom/fast-style-transfer
2. TensorFire (cc @antimatter15) is no longer maintained, but there are alternative libraries that you could use, like [TensorFlow.js](https://www.tensorflow.org/js)
