### ISSUE TITLE
several CONTENT_LAYERS support

### ISSUE THREAD

**Issue by Allycen** [anishathalye/neural-style#19]
Can you add support for several conv layers of CONTENT_LAYERS or tell what I need to do to implement it?

**Comment by anishathalye** [comment]
I'm not planning on adding it. But it should be easy enough. Look at the current implementation of `CONTENT_LAYER`, and then see how multiple `STYLE_LAYERS` are handled. You should be able to do something similar for content layers (use a weighted sum of multiple content layer losses).

**Comment by theSparta** [comment]
@anishathalye Can I submit a pull request for it? If yes, for multiple content images what should be the dimensions of the initial image or should there be multiple intial images?

**Comment by anishathalye** [comment]
It doesn't really make sense to support multiple content images. I don't think the results would make any sense.

Though if you do experiment with this and something interesting happens, feel free to send a pull request.
