### ISSUE TITLE
Default configuration

### ISSUE THREAD

**Issue by grant** [anishathalye/neural-style#2]
Hi Anish,

I'm trying to reproduce the results of your example and am not producing great results. I'm using the current configuration as provided (1000 iterations).

## Inputs
![content](https://cloud.githubusercontent.com/assets/744973/11540547/33d419c2-98e2-11e5-9d3f-c046d681aa1a.jpg)
![style](https://cloud.githubusercontent.com/assets/744973/11540552/37896f7c-98e2-11e5-8825-f6a6d08673eb.jpg)

## Output
![output1](https://cloud.githubusercontent.com/assets/744973/11540554/3b812c00-98e2-11e5-809a-4fd621f618e2.jpg)

## Expected
![1-output](https://cloud.githubusercontent.com/assets/744973/11540571/4ead3436-98e2-11e5-95a1-e1c220c62ba4.jpg)

As you can see, my result looks noisy and doesn't have smooth color blends.

Do you know the configuration you had to make your example output (and can we make that configuration the default)? Maybe I should try increasing `STYLE_WEIGHT`.

Cheers,
Grant

**Comment by anishathalye** [comment]
There were some issues with older versions of the code. Could you try again with the current HEAD (0883089f5818a1c85579ddfc417f43f27652b48e) and the inputs [here](https://github.com/anishathalye/neural-style/tree/9b107ee074490183b3c29062cda8ce6838f37bbd/examples)?

It should produce this as a result (1000 iterations, default settings):

![](https://raw.githubusercontent.com/anishathalye/neural-style/9b107ee074490183b3c29062cda8ce6838f37bbd/examples/1-output.jpg)

**Comment by anishathalye** [comment]
Gonna assume that this is resolved; feel free to re-open if not.
