### ISSUE TITLE
Only 26 iterations within 10 hours on CPU CORE i5 

### ISSUE THREAD

**Issue by zuoxingdong** [anishathalye/neural-style#20]
I am now using my laptop, Core i5 CPU only and TensorFlow 0.9,  to train a photo, and waited for 10 hours it only gets to iteration 26. Is it an expected performance on CPU ? It seems for full 1000 iteration it'll take more than a week for a single image. 

Is there a possibility to improve the speed ?

**Comment by anishathalye** [comment]
It depends on the size of the image.

If it's that slow on something like a 512x512 image, something is wrong with your setup.

**Comment by zuoxingdong** [comment]
@anishathalye  Thank you for the reply. You are right, both images was of the size 2000x1333, and now reduced to 128x128 to be much faster to complete 1000 iterations within an hour.

**Comment by anishathalye** [comment]
Yup. So a larger image takes a lot more compute power, but it also takes up a lot more RAM. With the size of the image you were using before, it might have exceeded your computer's physical RAM, so it might have been swapping (which would make it even slower than it would have been otherwise).

**Comment by limitforever** [comment]
Hello,I want to ask where I can get smaller training dataset?
