### ISSUE TITLE
compile for CUDA 7.5 and cuDNNv5 ?

### ISSUE THREAD

**Issue by hablema** [anishathalye/neural-style#23]
I'm not able to run it with CUDA 7.5 and cuDNNv5. Is there any other way besides downgrading my cuDNN to v4.

**Comment by anishathalye** [comment]
Not an issue with neural-style, it's an issue with TensorFlow.

https://www.tensorflow.org/versions/r0.10/get_started/os_setup.html

**Comment by hablema** [comment]
@anishathalye : Thanks for the reply. I downgraded it to v4 and it's working. I'm working on an EC2 g2.2xlarge and it takes 6-8 minutes for a 300 x 500 image. Is it the normal time or am i doing something wrong ? 

Anyhow, thanks for the project and great work.

**Comment by anishathalye** [comment]
Sounds a little slow, but within the right range.
