### ISSUE TITLE
Download a wrong imagenet vgg 

### ISSUE THREAD

**Issue by Zcating** [anishathalye/neural-style#25]
I use python3 to run your script, and it shows the following error:
>   File "neural_style.py", line 152, in <module>
    main()
  File "neural_style.py", line 130, in main
    checkpoint_iterations=options.checkpoint_iterations
  File "~/DeepLearn/neural-style-master/stylize.py", line 41, in stylize
    net, mean_pixel = vgg.net(network, image)
  File "~/DeepLearn/neural-style-master/vgg.py", line 25, in net
    mean = data['normalization'][0][0][0]
KeyError: 'normalization'

thank for help me

**Comment by Zcating** [comment]
I found the problem that I maybe download a wrong image net vgg....

**Comment by anishathalye** [comment]
See #4 #6 #12
