### ISSUE TITLE
CuDNN version

### ISSUE THREAD

**Issue by seanschang** [anishathalye/neural-style#26]
Hi I got the following error message: 

<code> Loaded runtime CuDNN library: 5103 (compatibility version 5100) but source was compiled with 4007 (compatibility version 4000).  If using a binary install, upgrade your CuDNN library to match.  If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration.
</code>

I'm using CUDA 7.5 and cuDNN 5.1. Am I supposed to downgrade cuDNN to 4.x? Thanks!

**Comment by anishathalye** [comment]
Idk, this is more of a TensorFlow problem rather than a neural-style problem. This might help: https://www.tensorflow.org/versions/r0.10/get_started/os_setup.html

**Comment by seanschang** [comment]
@anishathalye yeah you're right, this is a tensorflow problem, I didn't activate the virtualenv, the issue is solved by running `source ~/tensorflow/bin/activate`. Thank you so much!

**Comment by anishathalye** [comment]
Awesome, glad it got sorted out.
