### ISSUE TITLE
Aborted (core dumped)

### ISSUE THREAD

**Issue by fdcqsjn** [anishathalye/neural-style#28]
Hi,could you give me some advice to solve this problem?
``
CUDA_VISIBLE_DEVICES=1` python neural_style.py --content examples/1-content.jpg --styles examples/1-style.jpg --output examples/TF1.jpg  
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
E tensorflow/stream_executor/cuda/cuda_driver.cc:491] failed call to cuInit: CUDA_ERROR_NO_DEVICE
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:153] retrieving CUDA diagnostic information for host: icra-All-Series
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:160] hostname: icra-All-Series
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:185] libcuda reported version is: 367.48.0
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:356] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  367.48  Sat Sep  3 18:21:08 PDT 2016
GCC version:  gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 
"""
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] kernel reported version is: 367.48.0
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:293] kernel version seems to match DSO: 367.48.0
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

**Comment by anishathalye** [comment]
No idea… seems like an issue with your CUDA or TensorFlow setup rather than something wrong with this program.

Do any of the [examples](https://www.tensorflow.org/versions/r0.11/tutorials/index.html) on the TensorFlow website work for you?

What does `nvidia-smi` report?

**Comment by hunauchenym** [comment]
I have this question also with 4G GTX 960 and 8G RAM, It seem memory leak. The examples on the Tensorflow website all work well.

**Comment by fdcqsjn** [comment]
YES,The examples on the Tensorflow/models works well。

**Comment by hunauchenym** [comment]
How do you solve it?

**Comment by fdcqsjn** [comment]
No，now I use CPU only。Compiled another tensorflow not include cuda。

**Comment by hunauchenym** [comment]
I think GPU's storge（4G） is too small, It is reported that neural style works well on GTX 1070.

**Comment by anishathalye** [comment]
Right -- if the model is too big to fit in your GPU memory, it won't work. You can try scaling down.

**Comment by hunauchenym** [comment]
It is true reason that the image is too big, It seems that the image can not be bigger than 300k

**Comment by anishathalye** [comment]
I can do about 1000x1000px on my Maxwell Titan X.

**Comment by fdcqsjn** [comment]
Today I use the basic example (2-content 120K) and cuda，the neural_style.py work well. 
Maybe before my  <content file>  was to big(6MB).(I7 16GB GTX1070)
Thank you guys!

**Comment by ricoms** [comment]
I have a similar problem of OP.

I was using Ubuntu 1604, nvidia driver 384, CUDA 9.0, with tensorflow 1.4.1 and keras, running on a Gforce 1060 with 6Gb of memory. I have some codes for VGG16, Resnet and others. The sript was running perfectly with batches of 16 images.

Then I upgraded to CUDA 9.1, nvidia driver 390, tensorflow 1.7 and now the same script is ending abruptely on the first epoch with message `Aborted (core dumped)` ... even with a batch size of 1

help?
