### ISSUE TITLE
Required Arguments Error: --content, --styles, --output BUT I TYPED THEM

### ISSUE THREAD

**Issue by MotorCityCobra** [anishathalye/neural-style#29]
This must be some simple thing I'm over looking cause I've tried this within and without anaconda2 in python2.7 and python3.5. I tried to figure this out myself but this is always what I get for the first "argument" written in terminal.
Everything is in it's right place, the wheights are loaded and listed in the .py file. All requirements are installed. My photos are where the paths say they are.
 
$
$
$ python3.5 ~/path_to/neural_style.py -—content ~/anaconda2/envs/gnar/neural-style-master/A.jpg -—styles ~/anaconda2/envs/gnar/neural-style-master/S.jpg -—output /anaconda2/envs/gnar/neural-style-master/000.jpg
usage: neural_style.py [-h] --content CONTENT --styles STYLE [STYLE ...]
                       --output OUTPUT [--checkpoint-output OUTPUT]
                       [--iterations ITERATIONS] [--width WIDTH]
                       [--style-scales STYLE_SCALE [STYLE_SCALE ...]]
                       [--network VGG_PATH] [--content-weight CONTENT_WEIGHT]
                       [--style-weight STYLE_WEIGHT]
                       [--style-blend-weights STYLE_BLEND_WEIGHT [STYLE_BLEND_WEIGHT ...]]
                       [--tv-weight TV_WEIGHT] [--learning-rate LEARNING_RATE]
                       [--initial INITIAL]
                       [--print-iterations PRINT_ITERATIONS]
                       [--checkpoint-iterations CHECKPOINT_ITERATIONS]
neural_style.py: error: the following arguments are required: --content, --styles, --output
$

**Comment by anishathalye** [comment]
At least in the text you copied, you have some weird type of dashes: `-—content`. You should have `--content`.

**Comment by MotorCityCobra** [comment]
Thank you for pointing that out. I knew it was something simple. Sorry to bother you with something so small but I've been chasing my tale with this alone for hours.
My keyboard only has one - 'minus' symbol but I was copying and pasting the run command full of all those paths and my Macbook must have tried to get creative with the character.
I'm getting this now...
(py35) ANTHONYs-MacBook-Pro:~ AnthonyCelio$ python3.5 ~/anaconda2/envs/gnar/neural-style-master/neural_style.py --content ~/anaconda2/envs/gnar/neural-style-master/A.jpg --styles ~/anaconda2/envs/gnar/neural-style-master/S.jpg --output /anaconda2/envs/gnar/neural-style-master/000.jpg
Iteration 1/1000
Iteration 2/1000
Iteration 3/1000
Iteration 4/1000
Iteration 5/1000
Iteration 6/1000
Iteration 7/1000
Iteration 8/1000
Iteration 9/1000
[]

**Comment by anishathalye** [comment]
No worries. Glad you got it sorted out 😄

**Comment by MotorCityCobra** [comment]
If you're still there... Cause I always get weird problems with neural nets.... I'm up to 55 iterations, which is about 40 iterations per 20 minutes, or roughly 8 hours to get to 1000 iterations. Does that seem normal for a 13inch 2015 MacBook Pro (CPU only)?
Just wondering if I did it right. Nothing ever works out for me.

**Comment by anishathalye** [comment]
Depends on your image size. But yeah, CPU only is _really_ slow.
