### ISSUE TITLE
can neural-style run on Distributed TensorFlow?

### ISSUE THREAD

**Issue by zjjott** [anishathalye/neural-style#31]
as we know,neural-style is slow when iteration
can [Distributed TensorFlow](https://www.tensorflow.org/versions/r0.11/how_tos/distributed/index.html) help speed up iteration?
I read code of [stylize.py](https://github.com/anishathalye/neural-style/blob/master/stylize.py),and have no idea for parallel iteration

**Comment by anishathalye** [comment]
This is one way to make it fast: http://cs.stanford.edu/people/jcjohns/eccv16/

**Comment by zjjott** [comment]
@anishathalye thanks!

**Comment by anishathalye** [comment]
Ok, closing this for now, feel free to reopen if there's anything else.
