### ISSUE TITLE
How do you make the imagenet-vgg-verydeep-19.mat

### ISSUE THREAD

**Issue by menglin0320** [anishathalye/neural-style#32]
I'm working on a project and I need only part of vgg16 in my work. So I want to look at your code and figure out how to do that. But it seems like you didn't share your code for making imagenet-vgg-verydeep-19.mat.
Can I know more about how do you get the imagenet-vgg-verydeep-19.mat file

**Comment by anishathalye** [comment]
https://github.com/anishathalye/neural-style#requirements

**Comment by menglin0320** [comment]
What I need is vgg16 but it is vgg19. So I wonder how you get this or how you make this.

**Comment by anishathalye** [comment]
http://www.vlfeat.org/matconvnet/models/imagenet-vgg-verydeep-16.mat

more info: http://www.vlfeat.org/matconvnet/pretrained/

**Comment by anishathalye** [comment]
original paper: https://arxiv.org/pdf/1409.1556.pdf

**Comment by menglin0320** [comment]
Thanks

**Comment by anishathalye** [comment]
👍

**Comment by stephanedebove** [comment]
I downloaded imagenet-vgg-verydeep-16.mat, put it in the root folder, but got the message "Network imagenet-vgg-verydeep-19.mat does not exist". So I downloaded imagenet-vgg-verydeep-19.mat, put it in the root folder, and got the message " You're using the wrong VGG19 data".

What is the file I need and what should I do with it? Could you udpate README.md with the full instructions?

**Comment by anishathalye** [comment]
The README has full instructions: it includes a link for which file to download. See here: https://github.com/anishathalye/neural-style/tree/75188f06cac8140143ee32c35d68e1484d5f6687#data-files

Apparently, this continues to be a source of confusion, so I just updated the code to be compatible with both data formats. See the commit message for https://github.com/anishathalye/neural-style/commit/fcc43d79d2ea107c789d53424825ec9ffe8788f8 for details.

**Comment by anishathalye** [comment]
No problem, a lot of people have missed it :)

Glad you finally got it working!

**Comment by Keerthana2701** [comment]
imagenet-vgg-verydeep-19.mat when loaded gives the below error:
conv2d_v2() got an unexpected keyword argument 'filter'

i have downloaded the .mat file from https://www.vlfeat.org/matconvnet/pretrained/

how do i resolve this error?

**Comment by anishathalye** [comment]
https://github.com/anishathalye/neural-style#data-files

**Comment by Udayuk** [comment]
> imagenet-vgg-verydeep-19.mat when loaded gives the below error:
> conv2d_v2() got an unexpected keyword argument 'filter'
> 
> i have downloaded the .mat file from https://www.vlfeat.org/matconvnet/pretrained/
> 
> how do i resolve this error?

Hey..did you solve this error? Im getting the same error too.
