### ISSUE TITLE
Document how to run this in AWS

### ISSUE THREAD

**Issue by daj** [anishathalye/neural-style#37]
It would be great if there were instructions on how to run this in AWS, using an existing AMI (e.g. [this](http://ramhiser.com/2016/01/05/installing-tensorflow-on-an-aws-ec2-instance-with-gpu-support/)).  This would avoid people needing to configure all the dependencies, which was a real pain for me.  The instructions would need to explain how to save the images that are created - presumably you'd need to configure it to save them into S3 or somewhere you can retrieve them from.  

Feel free to close this as it's an enhancement suggestion. :-)

**Comment by anishathalye** [comment]
Great idea! It would be awesome if someone could do this; I'm sure people will find it useful.

**Comment by petronny** [comment]
I think you may need another implemention of neural style since tensorflow seems to be too much slower than others. 

Creating a 512x512 image with the torch implemention of neural style(`-backend cudnn -cudnn_autotune -num_iterations 700 -optimizer lbfgs`) takes about 80 sec on a GTX 970. But creating it with this implemention(`--optimizer lbfgs`) need 350+sec.

PS. I've added lbfgs support for this implemention, and I will create a PR later.

**Comment by anishathalye** [comment]
Yeah, this TF implementation is slower than the Torch implementation. (If anyone has time to figure out why, that would be great!)

@petronny getting a PR for adding L-BFGS would be awesome!

**Comment by lijingpeng** [comment]
I'm getting start to learn TF and deep learning. @daj I think Docker can help you run this in AWS, and I am working on it, later I will create a Pull request to add docker support.

**Comment by dovanchan** [comment]
You guys talking about AWS, I wanna ask ,Do you know if this training code can use 
in AWS Machine Learning?  If someone can use it to AWS machineLearning, then we don't need to buy a GPU instance.That will be very cheap.  so Is there anyone using AWS ML API?

**Comment by neilsh** [comment]
@dovanchan The AWS Machine Learning API currently pretty much only supports performing linear regression to perform simple classification or regression tasks. If you want to run tensorflow on AWS you'll need to use EC2, using either your own AMI or something like the AWS Deep Learning AMI.

https://aws.amazon.com/machine-learning/faqs/
https://aws.amazon.com/marketplace/pp/B06VSPXKDX
