### ISSUE TITLE
KeyError: 'normalization'

### ISSUE THREAD

**Issue by chenjiebin** [anishathalye/neural-style#39]
hello, I get an error when I run the command. I check the imagenet-vgg-verydeep-19.mat, it's md5sum  is same of the offical's. 
I don't get some idea. Could I get some help, thanks.

> $ python neural_style.py --content ./1-content.jpg --styles ./1-style.jpg --output ./out.jpeg 
> Traceback (most recent call last):
>   File "neural_style.py", line 152, in <module>
>     main()
>   File "neural_style.py", line 130, in main
>     checkpoint_iterations=options.checkpoint_iterations
>   File "/root/neural-style/stylize.py", line 41, in stylize
>     net, mean_pixel = vgg.net(network, image)
>   File "/root/neural-style/vgg.py", line 25, in net
>     mean = data['normalization'][0][0][0]
> KeyError: 'normalization'

python version:

> $ python --version 
> Python 2.7.5

list of dir:

> $ ll
> total 523236
> -rw-r--r--. 1 root root    245099 Oct 26 19:20 1-content.jpg
> -rw-r--r--. 1 root root    562577 Oct 26 19:22 1-style.jpg
> -rw-r--r--. 1 root root     35147 Oct 26 19:25 LICENSE.txt
> -rw-r--r--. 1 root root      3030 Oct 26 19:25 README.md
> drwxr-xr-x. 2 root root      4096 Oct 26 19:25 examples
> -rw-r--r--. 1 root root 534904783 Oct 27 02:17 imagenet-vgg-verydeep-19.mat
> -rw-r--r--. 1 root root      5820 Oct 26 19:25 neural_style.py
> -rw-r--r--. 1 root root      5357 Oct 26 19:25 stylize.py
> -rw-r--r--. 1 root root      5035 Oct 26 20:20 stylize.pyc
> -rw-r--r--. 1 root root      1964 Oct 27 02:40 vgg.py
> -rw-r--r--. 1 root root      2653 Oct 27 02:40 vgg.pyc

os version:

> $ cat /etc/os-release  
> NAME="CentOS Linux"
> VERSION="7 (Core)"
> ID="centos"
> ID_LIKE="rhel fedora"
> VERSION_ID="7"
> PRETTY_NAME="CentOS Linux 7 (Core)"
> ANSI_COLOR="0;31"
> CPE_NAME="cpe:/o:centos:centos:7"
> HOME_URL="https://www.centos.org/"
> BUG_REPORT_URL="https://bugs.centos.org/"
> CENTOS_MANTISBT_PROJECT="CentOS-7"
> CENTOS_MANTISBT_PROJECT_VERSION="7"
> REDHAT_SUPPORT_PRODUCT="centos"
> REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Comment by anishathalye** [comment]
See #4 #6 #12 #25
