### ISSUE TITLE
imagenet--vgg-verydeep-19.mat

### ISSUE THREAD

**Issue by YuanEZhou** [anishathalye/neural-style#41]
I want to know what's the structure of   imagenet-vgg-verydeep-19.mat.    Of course,I can get the detail structure  with the help of  scipy.io.loadmat().     But,I   think  it's not convenient . where can i get the detail description of   imagenet--vgg-verydeep-19.mat.    Can you give me a exact  link?
Thanks.

**Comment by anishathalye** [comment]
See #32 #33
