### ISSUE TITLE
System Freeze

### ISSUE THREAD

**Issue by harry0731** [anishathalye/neural-style#48]
First, thank you for this amazing work.
I'm using GTX 1080.
I can run your example pictures very well.
But when I use my own picture which I had already reduce the image to 764x615, the system freeze.
The program went well at first, but when the iterations is about 300 times, the system broke down.
The screen went black and the graphic card's fan runs loudly.
And the computer won't respond to anything that I had to shut it down.

Any suggestions ?
Thank you.

**Comment by anishathalye** [comment]
I do all my deep learning work on a headless box. If you don't run X using the same GPU that you're using for deep learning, you have more memory available for the GPGPU work.

In any case, running GPGPU code shouldn't make your entire system unstable, but that's not a problem with neural-style or TensorFlow…

**Comment by anishathalye** [comment]
You could check out this project that a friend made that has much lower memory requirements: https://github.com/lengstrom/fast-style-transfer

**Comment by harry0731** [comment]
Thank you.
But after I shut down X service, the system still broke down.
I will check out the fast style transfer.
Thanks again.

**Comment by anishathalye** [comment]
That has to do with your system setup, not with this code.
