### ISSUE TITLE
Why max pooling instead of average pooling as per paper?

### ISSUE THREAD

**Issue by ARTLAUROO** [anishathalye/neural-style#49]
Hi Anish Athalye, 

I am not sure if this is the appropriate way of communication, but I don't know what else to do. In your code you seem to use max pooling while in the neural style paper you referenced the authors claim that better results are obtained by using average pooling. I tried it out myself and there is a very noticeable difference in using one or the other. Average pooling makes the images look much smoother and more like the original content image. While max pooling makes the images more painting like.

I wondered if this was a deliberate choice of yours and if so, why did you choose max pooling over average pooling? I am just curious to know :)

Greetings!

PS Below attached two pictures, one generated with avg pooling, the other with max pooling, such that you can see it for yourself.

Average pooling:
![result-avg-pool](https://cloud.githubusercontent.com/assets/3845426/22292382/2e7a1fde-e30b-11e6-9f0c-a1131ce660c5.jpg)

Max pooling:
![result-max-pool](https://cloud.githubusercontent.com/assets/3845426/22292383/2e7a1f2a-e30b-11e6-8d94-a594bb1d702c.jpg)

Original content:
![face](https://cloud.githubusercontent.com/assets/3845426/22292415/6333527c-e30b-11e6-92c1-df47c9af0b49.jpg)

Style:
![woman-with-hat-matisse](https://cloud.githubusercontent.com/assets/3845426/22292427/71cdd3ac-e30b-11e6-9115-a014b8e90d89.jpg)

**Comment by anishathalye** [comment]
To be honest, I don't remember super well (it was about a year ago). It was a deliberate choice - I think with the examples I tried, max pooling looked nicer.

**Comment by ARTLAUROO** [comment]
Aah ok, was just curious
