### ISSUE TITLE
Validity of arguments should be checked before running

### ISSUE THREAD

**Issue by themightyoarfish** [anishathalye/neural-style#54]
When one mistypes the value for the `--output` parameter, the program will run for a possibly long time and then, upon trying to save the image, crash. It would be better to check before if the output file is actually writable.

**Comment by anishathalye** [comment]
Sure, that would be useful. Pull requests appreciated.

**Comment by themightyoarfish** [comment]
If I remember it, I'll make one tomorrow.

**Comment by neilsh** [comment]
@themightyoarfish @anishathalye PR #73 should fix this

**Comment by anishathalye** [comment]
fixed in a0fac87fbe7768e69d0ff6866596280a2905b93e.
