### ISSUE TITLE
key error ''

### ISSUE THREAD

**Issue by silverstone1903** [anishathalye/neural-style#57]
Hi!

I got this error end of the iterations. It prints content, style, tv and total loss then this error appears. I'm not a good Python coder so I didn't get any idea about it. By the way I'm using TF 1.0 on the Windows 7 with Anaconda3.

`Traceback (most recent call last):
  File "neural_style.py", line 156, in <module>
    main()
  File "neural_style.py", line 139, in main
    imsave(output_file, image)
  File "neural_style.py", line 152, in imsave
    scipy.misc.imsave(path, img)
  File "C:\Program Files\Anaconda3\lib\site-packages\scipy\misc\pilutil.py", line 197, in imsave
    im.save(name)
  File "C:\Program Files\Anaconda3\lib\site-packages\PIL\Image.py", line 1713, in save
    format = EXTENSION[ext]
KeyError: ''`

**Comment by anishathalye** [comment]
What flags/arguments did you provide?

**Comment by silverstone1903** [comment]
@anishathalye just `--iterations`. I set it for 50

**Comment by anishathalye** [comment]
You need to set a `--output` file

**Comment by silverstone1903** [comment]
@anishathalye I mean additionally I provide iterations. Of course I'm using content ,styles and output arguments

**Comment by anishathalye** [comment]
So can you provide the full command invocation?

**Comment by silverstone1903** [comment]
Now I noticed that I didn't put `.jpg` for output. It works properly, sorry for issue!
