### ISSUE TITLE
KeyError from data['normalization'] in vgg

### ISSUE THREAD

**Issue by DiegoSalazar** [anishathalye/neural-style#6]
```
KeyError                                  Traceback (most recent call last)
/Users/diego/src/neural-style/vgg.py in <module>()
----> 1 data['normalization']

KeyError: 'normalization'
```

What version of scipy should I install? I also downloaded imagenet-vgg-verydeep-19.mat from http://www.vlfeat.org/matconvnet/pretrained/. Hoping that's correct. Looks like your code loads that file from the neural-style directory yet it's not part of the repo. I only downloaded it after I tried running neural-style and it errored saying it couldn't load that file. Then I placed it in the neural-style directory and it worked up until the data['normalization'] line.

When I debug `data` I get a huge structure with these keys: 

```
data.keys()
dict_keys(['__globals__', 'meta', 'layers', '__header__', '__version__'])
```
The `__version__` key returns `'1.0'` 

my scipy version is `0.16.1`

**Comment by DiegoSalazar** [comment]
Just saw that's it way at the bottom of the readme.

**Comment by anishathalye** [comment]
Use the link given at the bottom of the readme, and make sure the md5 matches.

For more details, see #4.

**Comment by DiegoSalazar** [comment]
Just noticed that at the bottom, sorry!
