### ISSUE TITLE
W tensorflow/core/common_runtime/bfc_allocator.cc:274] ****************************************************************************************xxxxxxxxxxxx

### ISSUE THREAD

**Issue by buzai** [anishathalye/neural-style#60]
tensorflow/core/common_runtime/bfc_allocator.cc:696] 3 Chunks of size 6860800 totalling 19.63MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 13 Chunks of size 9437184 totalling 117.00MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 59686400 totalling 56.92MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 103601920 totalling 98.80MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:700] Sum Total of in-use chunks: 369.92MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:702] Stats: 
Limit:                   387907584
InUse:                   387890944
MaxInUse:                387907584
NumAllocs:                     622
MaxAllocSize:            147177472

W tensorflow/core/common_runtime/bfc_allocator.cc:274] ****************************************************************************************xxxxxxxxxxxx
W tensorflow/core/common_runtime/bfc_allocator.cc:275] Ran out of memory trying to allocate 2.44MiB.  See logs for memory state.
W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[1,533,400,3]

this is why?

**Comment by anishathalye** [comment]
not enough memory - see #28, #21

**Comment by anishathalye** [comment]
gonna close for now, if you have any more questions, feel free to reopen
