### ISSUE TITLE
program killed

### ISSUE THREAD

**Issue by Leslie-Fang** [anishathalye/neural-style#61]
I just run the program on my VPS ubuntu14.04 with 1G RAM
This program just run 1 iteration and be killed?
here is the report:

'Optimization started...
Iteration    1/1000
Killed'

what's problem?Is about the computation power?

**Comment by anishathalye** [comment]
almost surely, not having enough memory; see #60, #28, #21

**Comment by Leslie-Fang** [comment]
Thank you!

**Comment by anishathalye** [comment]
👍
