### ISSUE TITLE
--output cann`t support *.jpg

### ISSUE THREAD

**Issue by LySnake** [anishathalye/neural-style#65]
```
Iteration 1499/1500
Iteration 1500/1500
  content loss: 1.16644e+06
    style loss: 348997
       tv loss: 83460.1
    total loss: 1.59889e+06
Traceback (most recent call last):
  File "neural_style.py", line 206, in <module>
    main()
  File "neural_style.py", line 187, in main
    imsave(output_file, combined_rgb)
  File "neural_style.py", line 203, in imsave
    Image.fromarray(img).save(path, quality=95)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 1713, in save
    format = EXTENSION[ext]
KeyError: '.jgp'
```
I do not have a video card, use i5 6500 cpu, I spent 7 hours running a case, because I used the --output * .jpg，Please increase the friendliness of this question, thank you！

**Comment by anishathalye** [comment]
.jgp != .jpg

**Comment by LySnake** [comment]
oh no!   thanks

**Comment by avoroshilov** [comment]
@LySnake you can prevent wasting time on your machine by introducing unconditional save with some hardcoded name like `transfer_result.png` to avoid suffering consequences of mistakes like above, or e.g. when you don't have necessary folder created, or maybe permission issues, for example by adding line
```
imsave('transfer_result.png', combined_rgb)
```
just before this one:
https://github.com/anishathalye/neural-style/blob/master/neural_style.py#L187

This way you will always get stylize results no matter what, in this file, and also will have a copy in a place that you specified as output path, if everything went fine.

**Comment by anishathalye** [comment]
I think someone was thinking of fixing this in #54
