### ISSUE TITLE
VGG16-face

### ISSUE THREAD

**Issue by ginsongsong** [anishathalye/neural-style#67]
I have a dumb question, could I  use the vgg.py to load vgg-face.mat  model to creating face style?

I have changed the vgg.py network description as following:

Original VGG19 layer 
`   VGG19_LAYERS = (
    'conv1_1', 'relu1_1', 'conv1_2', 'relu1_2', 'pool1',

    'conv2_1', 'relu2_1', 'conv2_2', 'relu2_2', 'pool2',

    'conv3_1', 'relu3_1', 'conv3_2', 'relu3_2', 'conv3_3',
    'relu3_3', 'conv3_4', 'relu3_4', 'pool3',

    'conv4_1', 'relu4_1', 'conv4_2', 'relu4_2', 'conv4_3',
    'relu4_3', 'conv4_4', 'relu4_4', 'pool4',

    'conv5_1', 'relu5_1', 'conv5_2', 'relu5_2', 'conv5_3',
    'relu5_3', 'conv5_4', 'relu5_4'
)`

Change to VGG-16 layer
`VGG16_LAYERS = (
    'conv1_1', 'relu1_1', 'conv1_2', 'relu1_2', 'pool1',

    'conv2_1', 'relu2_1', 'conv2_2', 'relu2_2', 'pool2',

    'conv3_1', 'relu3_1', 'conv3_2', 'relu3_2', 'conv3_3',
    'relu3_3', 'pool3',

    'conv4_1', 'relu4_1', 'conv4_2', 'relu4_2', 'conv4_3',
    'relu4_3', 'pool4',

    'conv5_1', 'relu5_1', 'conv5_2', 'relu5_2', 'conv5_3',
    'relu5_3'
)`
After download the [imagenet-vgg-verydeep-16](http://www.vlfeat.org/matconvnet/models/beta16/imagenet-vgg-verydeep-16.mat) 
, it's work to use vgg16 model.
When I change the model to [vgg-face](http://www.vlfeat.org/matconvnet/models/beta16/vgg-face.mat)
, it will print error message as following:

`File "neural_style.py", line 177, in main
    checkpoint_iterations=options.checkpoint_iterations
  File "/neural-style/stylize.py", line 58, in stylize
    net = vgg.net_preloaded(vgg_weights, image, pooling)
  File "/neural-style/vgg.py", line 52, in net_preloaded
    kernels, bias = weights[i][0][0][0][0]
ValueError: too many values to unpack
`

Can anyone give me some idea to fix it?

**Comment by anishathalye** [comment]
Going to assume that this was either resolved or no longer relevant. If that's not the case, feel free to reopen.

**Comment by ljvmiranda921** [comment]
Just in case someone came across this problem, the error only comes out whenever I use `python2`. When I explicitly write:

```python
python3 neural_style.py [ARGS]
```

Then it works as expected.

cc: @anishathalye @ginsongsong

**Comment by anishathalye** [comment]
Huh, it shouldn't have anything to do with python2 vs python3 -- iirc this code is compatible with both. What exactly is the error you get with python2?

**Comment by ljvmiranda921** [comment]
The same error as reported @anishathalye. I can still replicate it in my machine (Ubuntu 16.04)

Breaks at Python 2.7 but works at Python 3.6. To be honest I still can’t pinpoint why it’s like that.

**Comment by anishathalye** [comment]
What if you use the latest commit in this repo?

**Comment by ashutoshn** [comment]
I can confirm that when I just ran python neural_style.py, I got the same error. But I ran it with python3, as suggested above, the script runs fine. (I cloned the source yesterday.)

**Comment by anishathalye** [comment]
@ashutoshn which commit are you using?

**Comment by anishathalye** [comment]
Should be fixed now. See the commit message in cbf6a645aa45d3cd0a404fc94d6be197c1ecf186 for an explanation.
