### ISSUE TITLE
Why should the style layer weights be normalized?

### ISSUE THREAD

**Issue by tobylyf** [anishathalye/neural-style#68]
The style loss in the older version which has no "tweak" simply add the loss of different style layers together. But in the latest version even when the style_layer_weight_exp is 1 all the loss will be 1/5 compare to the older version. Is it reasonable? Or the style_weight is correspondingly modified?

**Comment by anishathalye** [comment]
Hmm, so I don't remember exactly how this was changed in one of the latest PRs (ab0ad031e8ce1be0be1a1e6b6b97d0eb9ad93753). It's probably easiest to just look at the diff to understand what's changed.

**Comment by tobylyf** [comment]
It seems that you correspondingly multiplied STYLE_WEIGHT by 5 in neural_style.py and the value remains the same now.
