### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by zzz6519003** [anishathalye/neural-style#7]
```
➜  neural-style git:(master) ✗ python neural_style.py --content /Users/zhengzhongzhao/Desktop/IMG_0200.jpg --output 1.jpg --styles STYLE
Traceback (most recent call last):
  File "neural_style.py", line 122, in <module>
    main()
  File "neural_style.py", line 75, in main
    content_image = imread(options.content)
  File "neural_style.py", line 113, in imread
    return scipy.misc.imread(path).astype(np.float)
AttributeError: 'module' object has no attribute 'imread'
```
Thanks!

**Comment by anishathalye** [comment]
As it says in the readme, you should have [Pillow](https://pypi.python.org/pypi/Pillow) installed, because SciPy needs Pillow (or PIL) for some image-related functionality.

Running `pip install pillow` should do the trick. You can test if this worked by seeing if `python -c 'import PIL'` works successfully.

**Comment by zzz6519003** [comment]
thx man!
➜  neural-style git:(master) ✗ python neural_style.py --content /Users/zhengzhongzhao/Desktop/IMG_0200.jpg --output 1.jpg --styles

what kind of styles can i have

**Comment by anishathalye** [comment]
Anything -- feed in any image file. Paintings work well. See the examples in the `examples/` folder.

**Comment by zzz6519003** [comment]
cool!
```
➜  neural-style git:(master) ✗ python neural_style.py --content /Users/zhengzhongzhao/Desktop/IMG_0200.jpg --output 1.jpg --styles /Users/zhengzhongzhao/Desktop/IMG_0200.jpg
can't determine number of CPU cores: assuming 4
I tensorflow/core/common_runtime/local_device.cc:25] Local device intra op parallelism threads: 4
can't determine number of CPU cores: assuming 4
I tensorflow/core/common_runtime/local_session.cc:45] Local session inter op parallelism threads: 4


```

then the computer becomes super slow,
eats up 14GB memory, wondering how much time does it take normally

**Comment by anishathalye** [comment]
It depends on the output image size, which is specified by the `--width`argument.

**Comment by zzz6519003** [comment]
so if i just wanna have a simple output, i just set it --width 30, is that
ok? XD THX!

2016-01-01 3:31 GMT+08:00 Anish Athalye <notifications@github.com>:

> It depends on the output image size, which is specified by the --width
> argument.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/anishathalye/neural-style/issues/7#issuecomment-168237561>
> .
>



-- 

yours,

正中赵
about.me/zzz6519003
[image: 正中赵 on about.me]
  <http://about.me/zzz6519003>

**Comment by zzz6519003** [comment]
`.`

**Comment by anishathalye** [comment]
Huh? Is this not resolved?

**Comment by zzz6519003** [comment]
so if i just wanna have a simple output, i just set it --width 30, is that
ok? XD THX!

2016-01-01 3:31 GMT+08:00 Anish Athalye <notifications@github.com>:


dude  thx fo reply!

**Comment by anishathalye** [comment]
Yeah. You still need to set the content/style images and output file name.

**Comment by zzz6519003** [comment]
can u modify my script?  :+1:

**Comment by anishathalye** [comment]
Sorry, I don't have time to look at anything. Best of luck figuring it out! :)
