### ISSUE TITLE
raise ImportError(msg).dlopen Library not loaded.how come?need help

### ISSUE THREAD

**Issue by zs236** [anishathalye/neural-style#74]
**command** : $ python neural_style.py --help
Traceback (most recent call last):
  File "neural_style.py", line 8, in <module>
    from stylize import stylize
  File "/Applications/neural-style/stylize.py", line 3, in <module>
    import vgg
  File "/Applications/neural-style/vgg.py", line 3, in <module>
    import tensorflow as tf
  File "/Applications/anaconda/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  **File "/Applications/anaconda/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/Applications/anaconda/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 61, in <module>
    from tensorflow.python import pywrap_tensorflow**
  File "/Applications/anaconda/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/Applications/anaconda/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: dlopen(/Applications/anaconda/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so, 10): Library not loaded: @rpath/libcudart.8.0.dylib
  Referenced from: /Applications/anaconda/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
  Reason: image not found

Failed to load the native TensorFlow runtime.

See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#import_error

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

my env is Mac,and pip the reqirements.txt
**Successfully installed mock-2.0.0 pbr-2.0.0 protobuf-3.2.0 tensorflow-gpu-1.0.1**
and the https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#import_error has been removed,can you figure me out?

**Comment by anishathalye** [comment]
You need to either install the CPU-only version of TensorFlow or install dependencies like CUDA (see https://www.tensorflow.org/install/).

@neilsh this is why I was reluctant to specify a `requirements.txt` - it doesn't always "just work".
#72 #52

**Comment by zs236** [comment]
the --help can work now after I **pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/mac/tensorflow-0.8.0rc0-py2-none-any.whl** 
thankyou .
the other question jumped in.

**command** : python neural_style.py --content ./examples/1-content.jpg --styles ./examples/1-style.jpg --output ~/desktop/output_test/kkk.jpg 

/Applications/anaconda/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
Traceback (most recent call last):
  File "neural_style.py", line 206, in <module>
    main()
  File "neural_style.py", line 177, in main
    checkpoint_iterations=options.checkpoint_iterations
  File "/Applications/neural-style/stylize.py", line 39, in stylize
    vgg_weights, vgg_mean_pixel = vgg.load_net(network)
  File "/Applications/neural-style/vgg.py", line 24, in load_net
    mean = data['normalization'][0][0][0]
**KeyError: 'normalization'**

I already download imagenet-vgg-verydeep-19.mat 
LICENSE.txt                  requirements.txt
README.md                    stylize.py
examples                     stylize.pyc
imagenet-vgg-verydeep-19.mat vgg.py
neural_style.py              vgg.pyc
thankyou for your patience.

**Comment by anishathalye** [comment]
#4 #6 #12 #25 #39 #43 #46 #69

**Comment by zs236** [comment]
cool~~!  It works after downloads the right vgg-19 in ready.md and https://storage.googleapis.com/tensorflow/mac/tensorflow-1.1.0rc0-py2-none-any.whl.

**Comment by anishathalye** [comment]
👍 

Glad you got it working!
