### ISSUE TITLE
KeyError : 'normalization'

### ISSUE THREAD

**Issue by savan77** [anishathalye/neural-style#75]
I am trying to run this using following command:
python neural_style.py --content input.jpg --styles style.jpg --output output.jpg --iterations 50

and I got an error as follows,

Traceback (most recent call last):
  File "neural_style.py", line 206, in <module>
    main()
  File "neural_style.py", line 177, in main
    checkpoint_iterations=options.checkpoint_iterations
  File "C:\Users\savan77\Desktop\neural-style\stylize.py", line 39, in stylize
    vgg_weights, vgg_mean_pixel = vgg.load_net(network)
  File "C:\Users\savan77\Desktop\neural-style\vgg.py", line 24, in load_net
    mean = data['normalization'][0][0][0]
KeyError: 'normalization'

Just to verify, I loaded imagenet-vgg-verydeep-19.mat using scipy and printed keys, which are as follows:
dict_keys(['__globals__', '__version__', 'layers', 'meta', '__header__'])

As you can see there is no key named 'normalization'.
I downloaded pretrained model from here - http://www.vlfeat.org/matconvnet/pretrained/#downloading-the-pre-trained-models

**Comment by anishathalye** [comment]
#4 #6 #12 #25 #39 #43 #46 #69 #74

**Comment by anishathalye** [comment]
Okay, 6bb540dc89a6f0f87cfa24a951ac22db0cfeea65 should help people with this in the future.
