### ISSUE TITLE
How to tune parameters in Adam optimization?

### ISSUE THREAD

**Issue by flowice** [anishathalye/neural-style#77]
Compare to the original paper, my results using this implement is a little worse.
Is it caused by the Adam optimization rather than LBFGS in the original paper?
What is the difference of the the optimization method and how to tune parameters for better results?
I have no idea.

Thanks

**Comment by anishathalye** [comment]
yes it's Adam over LBFGS. Someone submitted a PR to add LBFGS support to this project (https://github.com/anishathalye/neural-style/pull/38) but they haven't fixed up their PR so it can be merged.

**Comment by flowice** [comment]
@anishathalye I have tried the method in #38 . The result is more stable than Adam.
However, the optimization became a little slower.

I also have not found the way to probe at iteration progress. 
According to the official doc,  variables subject to optimization are updated in-place at the end of optimization when using  external_optimizer.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/opt/python/training/external_optimizer.py#L246

**Comment by ProGamerGov** [comment]
I did some experimentation with Adam's parameters, and Neural-Style [here](https://github.com/jcjohnson/neural-style/issues/428#issuecomment-342618091). I am not sure if my results are repeatable in Python with Tensorflow, but it might be worth a try if the implementations are similar enough.
