### ISSUE TITLE
where is the content and style data??

### ISSUE THREAD

**Issue by ghost** [anishathalye/neural-style#78]

**Comment by anishathalye** [comment]
you supply it as a command line argument

**Comment by zhuqunxi** [comment]
![image](https://cloud.githubusercontent.com/assets/22273557/26230193/9e7b6af0-3c79-11e7-93a9-10a3544a6ea7.png)

what‘s wrong? after running the program, there is no output figure...

**Comment by anishathalye** [comment]
You didn't specify a valid output image path

**Comment by zhuqunxi** [comment]
![image](https://cloud.githubusercontent.com/assets/22273557/26231562/b586d53c-3c82-11e7-880b-c1276fc7213c.png)
Thank you very much and great thanks to your careful answer!
