### ISSUE TITLE
Why resize the style image?

### ISSUE THREAD

**Issue by HC-2016** [anishathalye/neural-style#80]
In the neural_style.py:
`style_images[i] = scipy.misc.imresize(style_images[i], style_scale * target_shape[1] / style_images[i].shape[1])`

Is it necessary to resize the style image so that it has the same height with content image?
Why height?

**Comment by anishathalye** [comment]
By resizing the style image, you get different sized style features appearing in your output (that's why it's a tunable parameter).

I don't remember why I provided this as a tunable parameter but also resized it to the height of the content image...
