### ISSUE TITLE
yield

### ISSUE THREAD

**Issue by unhandyandy** [anishathalye/neural-style#83]
I don't know much Python, but it seems the for loop in main()

`for iteration, image in stylize(`

doesn't begin evaluating until after the for loop in stylize.py

`for i in range(iterations):
`
ending with 

```
                     yield (
                         (None if last_step else i),
                         img_out
                     )

```
has completed.  In that case there is no utility in saving progress at checkpoints because all those images immediate overwrite each other.

Am i getting this wrong?

**Comment by anishathalye** [comment]
The for loop ending with a yield is a [generator expression](https://www.python.org/dev/peps/pep-0289/) -- the values are only forced when they're needed, so this works as intended, saving intermediate progress.

**Comment by unhandyandy** [comment]
Right, that's what I'm confused about: the entire generator is consumed at once, and all the checkpoint images are written to the same file, hence each immediately overwrites the previous one.

**Comment by anishathalye** [comment]
No, control goes back and forth between the code inside stylize and the code that saves the image.

It's logically equivalent to this:

```python
def f(i):
    return "work representing computation of step %d" % i

def stylize():
    for i in range(5):
        print("computing f(%d)" % i)
        res = f(i)
        yield res

def main():
    for intermediate_result in stylize():
        print("saving '%s'" % intermediate_result)

main()
```

If you run this, it prints:

```
computing f(0)
saving 'work representing computation of step 0'
computing f(1)
saving 'work representing computation of step 1'
computing f(2)
saving 'work representing computation of step 2'
computing f(3)
saving 'work representing computation of step 3'
computing f(4)
saving 'work representing computation of step 4'
```

**Comment by unhandyandy** [comment]
OK, thanks, I must have been calling the options incorrectly, I think I forgot to specify checkpoint-output.
