### ISSUE TITLE
Memory Allocation

### ISSUE THREAD

**Issue by yurikleb** [anishathalye/neural-style#86]
Hi, this is amazing piece of work!
I have a question regarding GPU memory allocation
when running neural_style.py it indicates I have 1.5gb available, but right after it starts iteration 1 it says: `ran out of memory trying to allocate 975.59MiB  `
`ran out of memory trying to allocate 278.55MiB  `
 ect..

the script runs fine but I wonder if this memory allocation issue affects performance?

please see attached screen shot.

Many thanks!

![screenshot from 2017-06-13 16-11-48](https://user-images.githubusercontent.com/12280733/27070248-3550be66-5053-11e7-9c3e-99150fd17d56.png)

**Comment by anishathalye** [comment]
I'm not super familiar with Tensorflow's allocator and scheduler, so I'm not sure.
