### ISSUE TITLE
Is it possible to use gpu to accelerate the process on laptops

### ISSUE THREAD

**Issue by dongchuant** [anishathalye/neural-style#9]
It takes about 6 hours to finish 1000 iterations with small-size images.
Is it possible to make it faster? 
Thank you.

**Comment by anishathalye** [comment]
Depends on the output image size and the speed of your GPU (and whether you've set up TensorFlow properly to use your GPU).

Takes about 5 minutes for a 512x512 image on my Titan X.

**Comment by dongchuant** [comment]
Can I use gpu on Macbook Pro?
I am not very familiar with computer architecture..

**Comment by dongchuant** [comment]
And which argument controls cpu or gpu being used?

**Comment by gauss256** [comment]
Takes about 5-6 minutes for me too, using a 980 Ti.

I don't think TensorFlow supports the GPU on a MacBook Pro yet.

**Comment by dongchuant** [comment]
@gauss256 I think so..And thanks

**Comment by anishathalye** [comment]
Gonna assume that this is resolved. If not, feel free to reopen.
