### ISSUE TITLE
ERROR:the following arguments are required: --content, --styles, --output

### ISSUE THREAD

**Issue by cucrui** [anishathalye/neural-style#90]
I cloned your code and try to run your code to get example's result,but it threw an error as following:
usage: neural_style.py [-h] --content CONTENT --styles STYLE [STYLE ...]
                       --output OUTPUT [--iterations ITERATIONS]
                       [--print-iterations PRINT_ITERATIONS]
                       [--checkpoint-output OUTPUT]
                       [--checkpoint-iterations CHECKPOINT_ITERATIONS]
                       [--width WIDTH]
                       [--style-scales STYLE_SCALE [STYLE_SCALE ...]]
                       [--network VGG_PATH]
                       [--content-weight-blend CONTENT_WEIGHT_BLEND]
                       [--content-weight CONTENT_WEIGHT]
                       [--style-weight STYLE_WEIGHT]
                       [--style-layer-weight-exp STYLE_LAYER_WEIGHT_EXP]
                       [--style-blend-weights STYLE_BLEND_WEIGHT [STYLE_BLEND_WEIGHT ...]]
                       [--tv-weight TV_WEIGHT] [--learning-rate LEARNING_RATE]
                       [--beta1 BETA1] [--beta2 BETA2] [--eps EPSILON]
                       [--initial INITIAL]
                       [--initial-noiseblend INITIAL_NOISEBLEND]
                       [--preserve-colors] [--pooling POOLING]
neural_style.py: error: the following arguments are required: --content, --styles, --output
Did I miss out something?

**Comment by anishathalye** [comment]
You need to supply the command line options

**Comment by limitforever** [comment]
How did you solve your problem?@cucrui

**Comment by anishathalye** [comment]
You need to supply the required command-line options.

**Comment by nilame** [comment]
can you explain more? im confused. how can i do this?
