### ISSUE TITLE
throwing an instance of 'std::bad_alloc'

### ISSUE THREAD

**Issue by brightlike** [anishathalye/neural-style#92]
terminate called after throwing an instance of 'std::bad_alloc'
what():  std::bad_alloc
Aborted (core dumped)
linux  /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 94
model name	: Intel(R) Xeon(R) CPU E3-1275 v5 @ 3.60GHz
stepping	: 3
microcode	: 0x1
cpu MHz		: 3600.000
cache size	: 4096 KB
physical id	: 0
siblings	: 3
core id		: 0
cpu cores	: 3
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes

**Comment by anishathalye** [comment]
out of memory?

**Comment by anishathalye** [comment]
going to assume this is resolved, feel free to reopen if not
