### ISSUE TITLE
Tweaking guide welcome

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [anishathalye/neural-style#94]
Apart from your introduction, do you have some tips on which images to choose or which settings work best with which kind of images?

Appreciate your work, btw.

**Comment by anishathalye** [comment]
Nope, I haven't written one. Contributions welcome.

**Comment by ErfolgreichCharismatisch** [comment]
I found that Similar lighting conditions are important. A sunny content image works well with a sunny style image. Also similar settings work well with similar settings, portrait for portrait, landscape for landscape. Anything above 1000 iterations does not seem to improve.

**Comment by anishathalye** [comment]
If you want to make a section in the wiki (https://github.com/anishathalye/neural-style/wiki) about this, we can link to it from the readme
