### ISSUE TITLE
Is there a way to make it work with bigger images?

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [anishathalye/neural-style#96]
Anything beyond 640 x 480 pixels leads to an out of memory error.

Is there a way to make it work with bigger images?

**Comment by Steven-N-Hart** [comment]
As a workaround, you can decrease the image size on the fly by modifying the `imread` function:

```def imread(path):
    img = scipy.misc.imread(path).astype(np.float)
    if len(img.shape) == 2:
        # grayscale
        img = np.dstack((img, img, img))
    elif img.shape[2] == 4:
        # PNG with alpha channel
        img = img[:, :, :3]
    return scipy.misc.imresize(img, size=(255, 255)) # change to this
```

**Comment by anishathalye** [comment]
Or get a GPU with more memory: I can handle ~1000x1000 images on my Titan X

**Comment by vitalykovalgit** [comment]
Is it possible to make it work on even bigger images like, 3000x3000 or 5000x4000 or even bigger, I do not care about time, how long it will take to process, just want to fix out of memory exception

**Comment by anishathalye** [comment]
You can do it on CPU using system memory, but it will take a very long time 😛 

Alternatively, you could try using [fast style transfer](https://github.com/lengstrom/fast-style-transfer) which uses an entirely different algorithm to do all processing in a feedforward way (once you train a model on a particular style).
