### ISSUE TITLE
Small images still run out memory

### ISSUE THREAD

**Issue by andycui97** [anishathalye/neural-style#97]
Having read issues #21, #28, #60, and #61 I've assumed that a GPU with 16GB memory should be more than able to handle images of size 64x64. 

Unfortunately I still experience crashes on the first iteration that have been described in #61. 

I've tried having the three sessions I could find defined in stylize.py to grow their memory allocation using 

`
config.gpu_options.allow_growth=True
 `

but the problem persists. 

Any ideas?

**Comment by anishathalye** [comment]
What GPU are you using?

**Comment by andycui97** [comment]
Tesla P100, I'm working on a DGX-1 machine.

**Comment by anishathalye** [comment]
Maybe something is wrong with your particular setup. I can do ~ 1000x1000 on my Titan X (Maxwell).
