### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'reshape'

### ISSUE THREAD

**Issue by JimReno** [anishathalye/neural-style#98]
I tried this:
`python neural_style.py --content ./examples/1-content.jpg --styles ./examples/1-style.jpg --output ./examples/test1.jpg
`
the program runs correctly，but it shows error at the end of the iteration:

`Iteration  997/1000
Iteration  998/1000
Iteration  999/1000
Iteration 1000/1000
content loss: 1.72365e+30
style loss: inf
tv loss: nan
total loss: nan
Traceback (most recent call last):
File "neural_style.py", line 206, in <module>main()
File "neural_style.py", line 177, in main
checkpoint_iterations=options.checkpoint_iterations
File "/home/test/work/neural-style/neural-style/stylize.py", line 160, in stylize
img_out = vgg.unprocess(best.reshape(shape[1:]), vgg_mean_pixel)
AttributeError: 'NoneType' object has no attribute 'reshape'
`

**Comment by anishathalye** [comment]
Wasn't able to reproduce. Feel free to reopen if this is still an issue.
